### PR TITLE
Create ukgovdatascience

### PR DESCRIPTION
**Pull request by ranms25**
I convert to yaml file from

## UK
* [UK Government Data Science](https://github.com/ukgovdatascience)

### CODE REVIEW

**Comment by szabgab** [comment]
The filename should end with .yaml

**Comment by ranms25** [comment]
> The filename should end with .yaml
@szabgab 
Oh sorry Some I did, some I didn't notice.
 From checking I saw that all the UK files were uploaded/merged, just want to make sure that's really the case, and it's all good.

**Comment by szabgab** [comment]
I think only one had .yaml ending, but I thought this time I'll give it a pass. Merged them and fixed them.

It would have been better to send the PR of the new file addition together with the removal of the line from the md file, something we managed to do at the end of the meeting.

Also I did not show, but in these files I also started to add a field called `country`.

So check them out.

In any case everything is fine with this batch, thank you!

**Comment by szabgab** [comment]
Oh and you don't need to mention me in comments where I am already involved as I get notified anyway.

**Pull request merged**
